version: '3'
services:
  bot:
    build: .
    env_file: ./.docker-compose.env
    restart: always
    volumes:
      - /data/tg-anon-chat-bot/logs:/usr/src/app/logs
    depends_on:
      - torproxy
      - redis
      - postgres

  # Used by Telegram Bot
  torproxy:
    image: dperson/torproxy
    restart: always
    expose:
      - '9050'

  redis:
    image: redis
    restart: always
    expose:
      - '6379'

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data/tg-anon-chat-bot/postgres-data:/var/lib/postgresql/data
    expose:
      - '5432'
